site_name: My Docs
docs_dir: ../Documentation/docs
site_name: RPG Paper Maker
repo_url: https://github.com/RPG-Paper-Maker/RPG-Paper-Maker
copyright: RPG Paper Maker Copyright (C) 2017-2019 Marie Laporte
pages:
    - Getting started: 'index.md' 
    - Basics:
        - 'Map editor basics': 'basics/map-editor-basics.md'
        - 'Manage your resources': 'basics/manage-your-resources.md'
    - Advanced: 'advanced.md'
    - FAQ: 'faq.md'