site_name: My Docs
docs_dir: ../Documentation/docs
site_name: RPG Paper Maker
repo_url: https://github.com/RPG-Paper-Maker/RPG-Paper-Maker
copyright: RPG Paper Maker Copyright (C) 2017-2020 Wano
theme: readthedocs
pages:
    - Getting started: 'index.md' 
    - Basics:
        - 'Map editor basics': 'basics/map-editor-basics.md'
        - 'Manage your resources': 'basics/manage-your-resources.md'
        - 'Tilesets & Collisions': 'basics/tilesets-and-collisions.md'
        - 'Variables overview': 'basics/variables-overview.md'
        - 'Objects & Events': 'basics/objects-and-events.md'
        - 'Event commands overview': 'basics/event-commands-overview.md'
        - 'Control the camera': 'basics/control-the-camera.md'
        - 'Battle system': 'basics/battle-system.md'
        - 'Window skins': 'basics/window-skins.md'
        - 'Title Screen & Game Over': 'basics/title-screen-and-game-over.md'
    - Advanced:
        - 'Action Battle System': 'advanced/abs.md'
    - Experts: 'experts.md'
    - FAQ: 'faq.md'